name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://ci.db?mode=rwc

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run backend for testing
        run: |
          cargo install sqlx-cli --no-default-features --features sqlite
          cargo sqlx db create
          cargo sqlx migrate run
          cargo build
          cargo run &
        working-directory: backend
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Test (local)
        run: ./gradlew test
      - name: Test (emulator)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          working-directory: ./frontend
          script: ./gradlew connectedCheck
      - name: Report
        uses: FlickerSoul/android-test-report-actions@v1.2
        with:
          working-directory: "./frontend"
          show-skipped: "true"
        if: ${{ always() }}
      - name: Lint
        run: |
          ./gradlew lint
          ./gradlew ktlintCheck
